CC = g++
CCFLAGS = -g -std=c++11

sets:	main.cpp Pathfinder.cpp Pathfinder.h PathfinderInterface.h
	$(CC) $(CCFLAGS)  -o maze main.cpp Pathfinder.cpp

clean:
	rm maze.exe out_file1.txt out_file2.txt out_file3.txt out_file4.txt out_file5.txt